-- جدول المنتجات والمخزون
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  price NUMERIC NOT NULL,
  description TEXT,
  colors TEXT[], -- e.g. ['Black', 'Grey']
  sizes TEXT[],  -- e.g. ['S', 'M', 'L', 'XL', 'XXL']
  image_url TEXT,
  in_stock BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIMEZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- جدول أسعار الشحن للمحافظات
CREATE TABLE shipping_rates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  governorate TEXT UNIQUE NOT NULL,
  cost NUMERIC NOT NULL
);

-- جدول الطلبات وتفاصيل العملاء
CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIMEZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  customer_name TEXT NOT NULL,
  phone TEXT NOT NULL,
  secondary_phone TEXT,
  governorate TEXT NOT NULL,
  full_address TEXT NOT NULL,
  landmark TEXT,
  promo_code TEXT,
  items JSONB NOT NULL, --تفاصيل المنتجات والمقاسات والالوان
  total_amount NUMERIC NOT NULL,
  shipping_cost NUMERIC NOT NULL,
  status TEXT DEFAULT 'Pending' -- Pending, Confirmed, Shipped, Delivered, Cancelled
);